version: "3.8"

services:
  postgres:
    image: postgres:14
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: storyboard
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

  graphql-engine:
    image: hasura/graphql-engine:v2.20.0
    ports:
      - "8081:8080"
    depends_on:
      - postgres
    environment:
      HASURA_GRAPHQL_DATABASE_URL: postgres://user:password@postgres:5432/storyboard
      HASURA_GRAPHQL_ENABLE_CONSOLE: "true"
      HASURA_GRAPHQL_ADMIN_SECRET: myadminsecretkey

  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "4173:4173"
    depends_on:
      - graphql-engine
    environment:
      DATABASE_URL: postgres://user:password@postgres:5432/storyboard
    networks:
      - app-network

volumes:
  postgres-data:

networks:
  app-network:
    driver: bridge
